### запрос сервису напрямую
POST http://localhost:7081/v1/sms-verification?PhoneNumber=111
Content-Type: application/json

{}

### через api-gateway
POST http://localhost:8088/v1/sms-verification?PhoneNumber=111
Content-Type: application/json

{}

###
GET http://localhost:7081/v1/sms-verification?Code=6574&ProcessGUID=de9d7e54-2b87-4f7c-bd7b-b896d4593dd6
Content-Type: application/json

### через api-gateway
GET http://localhost:8088/v1/sms-verification?Code=8550&ProcessGUID=ba4b74d9-445b-4d20-831b-93347def6764
Content-Type: application/json

